### ISSUE TITLE
Svelte Formatting with Flickity or any Attribute Initialization directly on HTML

### ISSUE THREAD

**Issue by TuanSiNguyen** [sveltejs/prettier-plugin-svelte#100]
Hi all,

I just started to learn Svelte and this plugin is really awesome.
However, I'm facing an issue with the conflict in way of binding data between Svelte and Flickity.

In details, When I tried to cut my Static HTML (including Flickity data binding on HTML) like below:
`<div class="carousel-items row" data-lqd-flickity='{"wrapAround": true, "autoplay": true, "pageDots": true, "prevNextButtons": true }'>`

ESLint show error "Expected }":
image
![image](https://user-images.githubusercontent.com/16921163/82927776-66bb5b00-9fab-11ea-894c-b6001c5fd585.png)

Then the quotes in html tags like `data=''` will be removed on formatting.

And the compiler doesn't run correctly anymore. I can see that it conflicts with the JavaScript expression.

I tried some ways like double expressions or other codes but it didn't work.
I think there must be a way to use these things together.

Hope someone can help me, It would be much appreciated.
Cheers,

**Comment by antony** [comment]
We don't answer support queries on github issues. I remember you asked this in chat earlier, and I gave you the answer, but you appear to have gone back to the incorrect way of doing things. The correct way is, as I mentioned earlier:

```
<div class="carousel-items row" data-lqd-flickity={{"wrapAround": true, "autoplay": true, "pageDots": true, "prevNextButtons": true }}'>
```

It sounds like you are having issues elsewhere with flickity, so please create a REPL as I mentioned, and post it in chat so that we can help.
