### ISSUE TITLE
Whitespace issue after a tag

### ISSUE THREAD

**Issue by mhatvan** [sveltejs/prettier-plugin-svelte#159]
**Describe the bug**
Might be related to prettier-plugin-svelte, but I am having this issue since a long time. 

In the first example in the REPL provided below, there is no white space as expected, in the 2nd example the tag opening and closing tag and the text are all on individual lines (like prettier formats it) and it seems to count as a white space.

**To Reproduce**
https://svelte.dev/repl/6eca3f26aee1427580c9781c0e3396a5?version=3.29.4

**Expected behavior**
No white space no matter how the code is formatted.

**Information about your Svelte project:**
- Your browser and the version: Brave 1.16.72

- Your operating system: Ubuntu Linux 20.10

- Svelte version: 3.29.4

- Whether your project uses Webpack or Rollup

**Comment by dummdidumm** [comment]
The bug is: the text should "hug" the start/end tags and not add line breaks/whitespace.
@ehrencrona before you jump in, I have a little rework of the children logic in the making which might also deal with this.

**Comment by ehrencrona** [comment]
So the bug is that the second `<p>` in the REPL formats to the first? Isn't the issue that the formatter would need to know whether the component is whitespace sensitive or not? We discussed this in #28 where we talked about using `prettier-ignore` or `<!-- display: block -->` for these situations.

I'm a bit confused by the whitespace being present in the output *after* the body ("...coffee") but not *before* it ("buy me..."). I remember the Svelte parser doing trimming somewhere but I'm not sure in which circumstances.

@dummdidumm let me know when the refactoring is done and if i can help at that point. I'll hold off until then.

**Comment by dummdidumm** [comment]
Oh right, I forgot about #28 . Prettier treats everything as whitespace sensitive except the block elements. Maybe we should do the same and switch it up. Right now everything is treated as a block except a specified list of inline-elements.
