### ISSUE TITLE
104.0.0 ignores settings and changed defaults (?)

### ISSUE THREAD

**Issue by dkzlv** [sveltejs/prettier-plugin-svelte#193]
After updating to 104.0.0 plugin started changing my code layout as if I set the settings to these:

```json
{
  "svelteSortOrder": "scripts-options-markup-styles",
  "svelteStrictMode": false,
  "svelteBracketNewLine": true
}
```

I didn't have any specific svelte settings set earlier, it just worked. I have tried to overwrite these settings in  `.prettierrc`, `prettier` in `package.json` and plain old vs code settings with this config:

```json
{
  "svelteSortOrder": "scripts-styles-options-markup",
  "svelteStrictMode": false,
  "svelteBracketNewLine": false,
  "svelteAllowShorthand": true,
  "svelteIndentScriptAndStyle": true
}
```

, but it keeps ignoring me (restarted Svelte plugin, VS Code, Mac).

Not sure what logs I can provide.

**Comment by dkzlv** [comment]
Just confirmed that after rolling back to 103.0.0 things go back to normal

**Comment by dummdidumm** [comment]
Do you have `prettier-plugin-svelte` in your `package.json`, and if so, which version?

**Comment by dkzlv** [comment]
@dummdidumm No, I do not. I have `prettier@2.2.1`.

**Comment by dummdidumm** [comment]
Found the culprit. The sort order you have given is not part of [the choices](https://github.com/sveltejs/prettier-plugin-svelte/blob/master/src/options.ts#L26), needs to be added.

**Comment by dummdidumm** [comment]
Mhm I cannot reproduce this with the info you provided.. very strange.

**Comment by dkzlv** [comment]
I tried to setup a new project and it works fine, just like it should.
So it seems to me I mess up the configuration somehow. Will try to dig into this.

**Comment by dummdidumm** [comment]
Possibly related https://github.com/sveltejs/language-tools/issues/764

**Comment by chimp1nski** [comment]
Just letting you know that I have the exact same issue.
Trying to figure out if it comes from the plugin or VS code extension.

**Comment by dummdidumm** [comment]
If there's a `.prettierrc` present, all options of the extension are ignored. This matches Prettier's standard behavior. 
If you don't set the Svelte extension as the primary formatter for Svelte files and have the Prettier extension installed, the options are ignored, too, because then the Prettier extension is used for formatting which knows nothing about options of other extensions. 
Could you all please confirm whether or not these are the reasons why it does not work for you?

**Comment by dkzlv** [comment]
@dummdidumm 

What I found:

1. I removed Eslint extension and Prettier extensions, and also removed them from my deps (just to be extremely sure). Nothing changes my code on save except Svelte's extension
2. I've removed `prettier` key from `package.json`, and I never had `.prettierrc` file
3. I've set the Svelte for VS Code settings to those I need as described in the first message

It started working fine again!

Then I added a few keys, that are not related to Svelte:

```
    "trailingComma": "all",
    "tabWidth": 2,
    "arrowParens": "avoid",
    "semi": true,
    "singleQuote": true,
    "printWidth": 100,
```

It suddenly stopped formatting the file correctly, styles went after markup again.

I've added svelte-related settings to `package.json`.

```
    "svelteSortOrder": "scripts-styles-options-markup",
    "svelteStrictMode": false,
    "svelteBracketNewLine": false,
    "svelteAllowShorthand": true,
    "svelteIndentScriptAndStyle": true
```

It started to work again!

So, I think, in the end something changed in the way settings merge, or the defaults changed, I dunno.
But my issue is now fixed.

**Comment by dummdidumm** [comment]
> Then I added a few keys, that are not related to Svelte:

Where did you add them? `.prettierrc`? If so - that's expected behavior. As soon as something is found in a  `.prettierrc` or `package.json` those options are used and the options set via the extension are ignored - there is no merge of options. This makes sense because you might collaborate on code where a `.prettierrc` is present but not all defaults are specifically listed, but it's still expected that these defaults are used instead of you local overrides.

**Comment by dkzlv** [comment]
@dummdidumm I added them to `package.json`.

Yes, thanks for the clarifications. I'll close the issue since the solution to this problem is to specify all the settings for the plugin.
