### ISSUE TITLE
Combine exports and imports

### ISSUE THREAD

**Issue by rupesh-raj** [sveltejs/prettier-plugin-svelte#229]
Hi,
I would like to know if the plugin supports combining all exports at one place and all exports to one place.
If not could this be marked as a feat request?
For instance if this is the original code
```
	export let var1;


	import { Chart } from '@abc/xyz';
	export let var2 = 400;
	import { onMount, afterUpdate, onDestroy } from 'svelte';
```
The code after running prettier could become
```	
        export let var1;
	export let var2 = 400;

	import { Chart } from '@abc/xyz';
	import { onMount, afterUpdate, onDestroy } from 'svelte';
```

TIA

**Comment by dummdidumm** [comment]
This is a request for which the preferences may differ greatly between the users. I think this is a step too far for a code formatter to implement. Moreover, since we use Prettier's formatter for formatting the script contents, you'd need to open your feature request there.
Btw the [Svelte for VS Code](https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode) extension supports "Organize Imports" which will place these in order at the top of the script.

**Comment by MarArMar** [comment]
@dummdidumm 
"Btw the [Svelte for VS Code](https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode) extension supports "Organize Imports" which will place these in order at the top of the script."

I do not see that option anywhere on the marketplace page nor the https://github.com/sveltejs/prettier-plugin-svelte page
