### ISSUE TITLE
svelteSortOrder none causes style and script tags to be removed when they are at the end of the file

### ISSUE THREAD

**Issue by acls** [sveltejs/prettier-plugin-svelte#406]
With the option `  svelteSortOrder: 'none',` in my `.prettierrc.js` file, the script and style tags are removed when they are the last element in the file.

This file:
```svelte
<div></div>
<style></style>
<script></script>
```
will be formatted to:
```svelte
<div></div>
<style></style>
```
and formatting it again it will become:
```svelte
<div></div>
```

But those tags won't be removed when the markup is at the end, so when this file is formatted it stays the same:

```svelte
<style></style>
<script></script>
<div></div>
```

**Comment by KostisFioravantes** [comment]
The same bug here. I think that preventing a formatter from completely removing source code should be a priority. Honestly svelteSortOrder none is useless as long as this bug stays unfixed.

**Comment by andreasputlitz** [comment]
This just happened to me. I switched to "none", because prettier kept removing my comments after the style tags. And now ALL my style tags are gone and can not be recovered.

**Comment by andreasputlitz** [comment]
I just understood it happens when using the #region markers. If you open a region, but don't close it, the style tags will be erased. I was adding region markers to my files, and all my style have been removed from the pages, because first you need to add an open region-marker, before you can close it. But inbetween all the style tags have been remove. Since the style tags are at the end, it didn't realize it until running the app again way later.

No problem:

`

<style>
	@import url('/src/global.css');
</style>


`

This will lead to everything after the last markup tag will disappearing:

`

<style>
	@import url('/src/global.css');
</style>
`

**Comment by andreasputlitz** [comment]
Honestly, I cannot understand, why you would create a formatter that simply deletes hundreds of lines of codes. Hours of work gone.

**Comment by andreasputlitz** [comment]
I found a workaround as long as this isn't fixed.

If the script-tags are followed by an HTML-comment, apparently they don't get erased.

So, this...

```
<body></body>
<style></style>
<!--  -->
```

Is fine.

While this...

```
<body></body>
<style></style>
```

will be reformatted, to this:

```
<body></body>
```

It doesn't matter if the style-tags contain code or not. This is how I found out, because all of a sudden my app didn't have any styles anymore, after setting `svelteSortOrder: none`.
