### ISSUE TITLE
Using rules and config from .eslintrc.js

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/prettier-plugin-svelte#50]
I have

```js
{
  "extends": "standard"
}
```

(which comes from https://github.com/standard/eslint-config-standard#usage) in my `.eslintrc.js` and I'm wondering why this doesn't work in `<script></script>` part of my `.svelte` files.

What rules is this plugin following?

**Comment by orlov-vo** [comment]
> What rules is this plugin following?

This plusgin using [original Prettier formatting](https://prettier.io) for JS code inside `<script></script>`. It doesn't read any eslint rules for formatting...

If you want to lint your code inside script blocks in `.svelte` files via `eslint` look for [`eslint-plugin-svelte3`](https://github.com/sveltejs/eslint-plugin-svelte3).

**Comment by frederikhors** [comment]
@orlov-vo thanks for your answer.

**Reproduction project**: https://github.com/frederikhors/svelte3-vscode-eslint

Using this in command line: `npx eslint --fix .\src\*` works good, it changes `App.svelte` and `main.js` as I want: following `standard.js` rules.

I'm using https://github.com/UnwrittenFun/svelte-vscode and in VS Code it doesn't work.

**Comment by peterbabic** [comment]
Still, it is possible to integrate [linters](https://prettier.io/docs/en/integrating-with-linters.html) into prettier, so you can have some rules following your liking. I can have them applied to .js (eslint) or .css (stylelint) files, but .svelte files in the same folder would not follow the new rules.

Would it be possible for this plugin to follow rules of the integrated linters instead of the prettier standard ones?

**Comment by dummdidumm** [comment]
As stated in the [newest Prettier docs](https://prettier.io/docs/en/integrating-with-linters.html), using packages like `eslint-plugin-prettier` or any other form of direct interaction of prettier and eslint is no longer recommended. Instead, use a preset configuration which turns off all Eslint rules which conflict with prettier and then just format first with prettier and run the linter afterwards.
Since prettier is an opinionated code formatting tool which comes with a very limited set of options, enhancements to those are very unlikely, more specifically the two mentioned above will not be part of the options.
