### ISSUE TITLE
Any instructions for use with webstorm?

### ISSUE THREAD

**Issue by QuantumInformation** [sveltejs/prettier-plugin-svelte#61]

**Comment by orlov-vo** [comment]
Try to use [Prettier plugin](https://plugins.jetbrains.com/plugin/10456-prettier) for it. I think you should configure Prettier via `.prettierrc` like this:

```json
{
  "tabWidth": 4,
  "printWidth": 120,
  "overrides": [
    {
      "files": "*.svelte",
      "options": {
        "parser": "svelte",
        "svelteSortOrder": "scripts-markup-styles",
        "svelteBracketNewLine": true
      }
    }
  ]
}
```

**Comment by QuantumInformation** [comment]
thx @orlov-vo

**Comment by pbastowski** [comment]
It's been a year since this question was first answered and the answer is currently simpler than before. 

WebStorm now supports Prettier and within its settings you can configure which version of Prettier to use. I have installed Prettier and the Svelte plugin globally.

`npm i -g prettier prettier-plugin-svelte`

This is almost enough for WebStorm to be able to format prettier files. The only thing to do is include the `.svelte` extension in Prettier config, see "Run for files:", below.

![image](https://user-images.githubusercontent.com/5649024/116853043-aa740700-abf5-11eb-9c4b-0b4949a8ee09.png)
